export const types ={
    newRestaurant:'[Restaurtant] create',
    listRestaurant:'[Restaurtant] list',
    FETCH_RESTAURANTS_SUCCESS:'[Restaurtant] FETCH_RESTAURANTS_SUCCESS',
    FETCH_RESTAURANTS_ERROR:'[Restaurtant] FETCH_RESTAURANTS_ERROR',
    FETCH_RESTAURANTS_REQUEST:'[Restaurtant] FETCH_RESTAURANTS_REQUEST',
    DISH_ADD:'[Restaurtant] DISH_ADD',
    DISH_EDIT:'[Restaurtant] DISH_EDIT',
    DISH_DELETE:'[Restaurtant] DISH_DELETE',
    RESTAURANT_NEW:'[Restaurtant] RESTAURANT_NEW',
    RESTAURANT_SAVE_REQUEST:'[Restaurtant] RESTAURANT_SAVE_REQUEST',
    RESTAURANT_SAVE_SUCCESS:'[Restaurtant] RESTAURANT_SAVE_SUCCESS',
    RESTAURANT_LOAD_REQUEST:'[Restaurtant] RESTAURANT_LOAD_REQUEST',
    RESTAURANT_LOAD_SUCCESS:'[Restaurtant] RESTAURANT_LOAD_SUCCESS',
    RESTAURANT_LOAD_ERROR:'[Restaurtant] RESTAURANT_LOAD_ERROR',

    RESTAURANT_UPLOAD_FILE_REQUEST:'[Restaurtant] RESTAURANT_UPLOAD_FILE_REQUEST',
    RESTAURANT_UPLOAD_FILE_SUCCESS:'[Restaurtant] RESTAURANT_UPLOAD_FILE_SUCCESS',
    RESTAURANT_UPLOAD_FILE_ERROR:'[Restaurtant] RESTAURANT_UPLOAD_FILE_ERROR',



//----UI REDUCER  - TYPES
UI_LOADING_REQUEST:'[UI] UI_LOADING_REQUEST',
UI_LOADING_SUCCESS:'[UI] UI_LOADING_SUCCESS',
UI_LOADING_ERROR:'[UI] UI_LOADING_ERROR',


UI_SHOW_SUCCESS_MESSAGGE:'[UI] UI_SHOW_SUCCESS_MESSAGGE',
UI_SHOW_ERROR_MESSAGGE:'[UI] UI_SHOW_ERROR_MESSAGGE',

}